# Site settings
title: Thoughts | Shreyas Bapat
description: "Weird Thoughts, Useful Thoughts, Just Thoughts"
baseurl: "/"
url: "http://blog.shreyasb.dev/"

# User settings
username: Shreyas Bapat
user_title: Software Developer
email: hello@shreyasb.com
twitter_username: astroshreyas
github_username:  shreyasbapat
linkedin_public_url: shreyasbapat
disqus_username: shreyasbapat
profile_picture: https://avatars1.githubusercontent.com/u/24257914?s=400&u=e4b3468682fb947f7b53a8458086822b39fb38a0&v=4
# Google services
google_analytics: UA-173548001-2
disqus:
    shortname:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: posts
      key_trigger: 2
    - title: series
      url: series
      key_trigger: 3
    - title: tags
      url: tags
      key_trigger: 4
    - title: about me
      url: about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/shreyasbapat
      external: true
      new_tab: true
      key_trigger: g
    - title: twitter
      external: true
      url: https://twitter.com/astroshreyas
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: poliastro
    url: https://github.com/poliastro/poliastro
  - name: EinsteinPy
    url: https://github.com/einsteinpy/einsteinpy
  - name: FurryTails
    url: https://furrytails.in
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
