# Site settings
title: Thoughts | Shreyas Bapat
description: "A blog by a developer turned into an Astronomer who is basically a Electrical Engineer"
baseurl: "/" 
url: "http://shreyasb.com/thoughts/"

# User settings
username: Shreyas Bapat
user_title: Software Developer
email: info@shreyasb.com
twitter_username: shreyasbapat99
github_username:  shreyasbapat
linkedin_public_url: shreyasbapat
disqus_username: shreyasbapat
profile_picture: https://avatars1.githubusercontent.com/u/24257914?s=400&u=e4b3468682fb947f7b53a8458086822b39fb38a0&v=4

disqus:
    shortname:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/shreyasbapat
      new_tab: true
      key_trigger: g
    - title: twitter
      url: https://twitter.com/shreyasbapat99
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: poliastro
    url: https://github.com/poliastro/poliastro
  - name: downy
    url: https://github.com/loadpy/downy
  - name: astroquery
    url: https://github.com/astropy/astroquery

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
